# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /c/Users/Dylan/Documents/Syracuse/my-instruction-simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /c/Users/Dylan/Documents/Syracuse/my-instruction-simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/Dylan/Documents/Syracuse/my-instruction-simulator/CMakeFiles /c/Users/Dylan/Documents/Syracuse/my-instruction-simulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/Dylan/Documents/Syracuse/my-instruction-simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw2

# Build rule for target.
hw2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hw2
.PHONY : hw2

# fast build rule for target.
hw2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/build
.PHONY : hw2/fast

architecture/Architecture.o: architecture/Architecture.cpp.o
.PHONY : architecture/Architecture.o

# target to build an object file
architecture/Architecture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Architecture.cpp.o
.PHONY : architecture/Architecture.cpp.o

architecture/Architecture.i: architecture/Architecture.cpp.i
.PHONY : architecture/Architecture.i

# target to preprocess a source file
architecture/Architecture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Architecture.cpp.i
.PHONY : architecture/Architecture.cpp.i

architecture/Architecture.s: architecture/Architecture.cpp.s
.PHONY : architecture/Architecture.s

# target to generate assembly for a file
architecture/Architecture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Architecture.cpp.s
.PHONY : architecture/Architecture.cpp.s

architecture/Executor.o: architecture/Executor.cpp.o
.PHONY : architecture/Executor.o

# target to build an object file
architecture/Executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Executor.cpp.o
.PHONY : architecture/Executor.cpp.o

architecture/Executor.i: architecture/Executor.cpp.i
.PHONY : architecture/Executor.i

# target to preprocess a source file
architecture/Executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Executor.cpp.i
.PHONY : architecture/Executor.cpp.i

architecture/Executor.s: architecture/Executor.cpp.s
.PHONY : architecture/Executor.s

# target to generate assembly for a file
architecture/Executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Executor.cpp.s
.PHONY : architecture/Executor.cpp.s

architecture/Parser.o: architecture/Parser.cpp.o
.PHONY : architecture/Parser.o

# target to build an object file
architecture/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Parser.cpp.o
.PHONY : architecture/Parser.cpp.o

architecture/Parser.i: architecture/Parser.cpp.i
.PHONY : architecture/Parser.i

# target to preprocess a source file
architecture/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Parser.cpp.i
.PHONY : architecture/Parser.cpp.i

architecture/Parser.s: architecture/Parser.cpp.s
.PHONY : architecture/Parser.s

# target to generate assembly for a file
architecture/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Parser.cpp.s
.PHONY : architecture/Parser.cpp.s

architecture/Registers.o: architecture/Registers.cpp.o
.PHONY : architecture/Registers.o

# target to build an object file
architecture/Registers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Registers.cpp.o
.PHONY : architecture/Registers.cpp.o

architecture/Registers.i: architecture/Registers.cpp.i
.PHONY : architecture/Registers.i

# target to preprocess a source file
architecture/Registers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Registers.cpp.i
.PHONY : architecture/Registers.cpp.i

architecture/Registers.s: architecture/Registers.cpp.s
.PHONY : architecture/Registers.s

# target to generate assembly for a file
architecture/Registers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Registers.cpp.s
.PHONY : architecture/Registers.cpp.s

architecture/Stack.o: architecture/Stack.cpp.o
.PHONY : architecture/Stack.o

# target to build an object file
architecture/Stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Stack.cpp.o
.PHONY : architecture/Stack.cpp.o

architecture/Stack.i: architecture/Stack.cpp.i
.PHONY : architecture/Stack.i

# target to preprocess a source file
architecture/Stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Stack.cpp.i
.PHONY : architecture/Stack.cpp.i

architecture/Stack.s: architecture/Stack.cpp.s
.PHONY : architecture/Stack.s

# target to generate assembly for a file
architecture/Stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/architecture/Stack.cpp.s
.PHONY : architecture/Stack.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hw2"
	@echo "... architecture/Architecture.o"
	@echo "... architecture/Architecture.i"
	@echo "... architecture/Architecture.s"
	@echo "... architecture/Executor.o"
	@echo "... architecture/Executor.i"
	@echo "... architecture/Executor.s"
	@echo "... architecture/Parser.o"
	@echo "... architecture/Parser.i"
	@echo "... architecture/Parser.s"
	@echo "... architecture/Registers.o"
	@echo "... architecture/Registers.i"
	@echo "... architecture/Registers.s"
	@echo "... architecture/Stack.o"
	@echo "... architecture/Stack.i"
	@echo "... architecture/Stack.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

